name: Formatting

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install clang-format
      run: sudo apt-get update && sudo apt-get install -y clang-format

    - name: Run clang-format
      run: |
        find . -name '*.cpp' -o -name '*.h' | xargs clang-format -i
        git diff --exit-code